#!/bin/sh

#  (C) Copyright 2005 Przemys³aw Pawe³czyk <przemoc@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License Version 2 as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Example of how to use pcspk with option -n | --note
#
# Takako Minekawa - Fantastic Cat (beginning)

TEMPO=140
INTRO="a47 C57 e57 e57 a47 C57 e57 e57 a47 C57 e57 e57 C57 e57 F57 e57"
MAIN1="P07 e53 P07 e57 C57 C57 a43 P07 P03 P03 P03 P07 e57 e57 e57 e57 e57 C57 C57 a43 P03 P03 P03 P03"
MAIN2="P07 a53 P07 a57 F57 F57 d53 P07 P03 P03 P03 P07 e57 e57 e57 e57 e57 C57 C57 a43 P03 P03 P03 P03"
MAIN3="B53 P07 G53 P03 a53 e53 P07 e57 C53 a43 P07 P00"
MELODY="$TEMPO $INTRO $INTRO $INTRO $INTRO $MAIN1 $MAIN2 $MAIN3"

echo "$MELODY" | pcspk -n