#!/bin/sh

#  (C) Copyright 2005 Przemysaw Paweczyk <przemoc@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License Version 2 as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Example of how to use pcspk with option -n | --note
#
# J.S.Bach fugue in D minor (fragment)

MELODY="240 A47 G47 A47 F47 A47 E47 A47 D47 A47 d47 A47 D47 A47 E47 A47 F47 A47 A37 A47 H37 A47 d47 A47 D47 A47 d47 A47 D47 A47 E47 A47 P47 D57 C57 D57 B47 D57 A47 D57 G47 D57 g47 D57 G47 D57 A47 D57 B47 D57 D47 D57 E47 D57 g47 D57 G47 D57 g47 D57 G47 D57 A47 D57 G43"

echo "$MELODY" | pcspk -n