# dirs
PREFIX=/usr/local
ETCDIR=$(PREFIX)/etc
BINDIR=$(PREFIX)/bin
SBINDIR=$(PREFIX)/sbin

# cmds
CC=gcc
CP=cp
RM=rm -fr
LN=ln
CD=cd
SED=sed
CHM=chmod
GET=wget
MKD=mkdir -p
TCH=touch
ECHO=echo -e
WHICH=which
INSTALL=install
