# dirs
PREFIX=/usr/local
ETCDIR=$(PREFIX)/etc
BINDIR=$(PREFIX)/bin
SBINDIR=$(PREFIX)/sbin

# cmds
CC=gcc
CP=cp
RM=rm -f
LN=ln
CD=cd
SED=sed
CHM=chmod
GET=wget
MKD=mkdir -p
ECHO=echo -e
INSTALL=install